### ISSUE TITLE
Just a Hi

### ISSUE THREAD

**Issue by bennukem** [dwarfhack/mmo#1]
Yo !

Not an issue, just I am reading your blog about your project. I have some interest in. I am starting with Rust too.
Interesting things but maybe you focus too much on network side.
UDP can be useful in some fast action games, but it can be many MMO with more slow interactions and use TCP.
I can see you are trying to do a ultimate server, maybe have to think about which game first.

**Comment by trimoq** [comment]
Hi @bennukem,
first off, thanks for your interest in the project and blog!

You are right, back when I wrote the blog posts in 2020, i went into the wrong direction, getting carried away by network related topics.

The current code in the repo is no longer related to those early experiments, I changed my focus on providing primitives for the core game loop in such projects. It will take a few more days though until the new blogposts are ready.

Regarding the use of TCP and UDP, I guess you may partially be right.
I did some [work](https://github.com/trimoq/pandars) with a very popular MMO, that in fact uses TCP. 
So you are completely right, you can get away building massive worlds using TCP as your transport.
However, newer titles in the genre use UDP instead, e.g. see [NewWorld](https://www.amazongames.com/en-us/support/new-world/articles/port-forwarding) or a mixture of both ( [BdO](https://portforward.com/black-desert-online/) and [Veloren](https://veloren.net/devblog-57/) )

For this project, the networking part currently is no longer the main focus, since projects like [enet](https://crates.io/crates/enet) and [raknet](https://github.com/facebookarchive/RakNet) have solved many of the game-related problems regarding the usage of transport protocols.

Btw, I started to write two new blogposts a few weeks ago on the new direction of the project, hence the new commit out of the blue.
Since your statement reflect my thought a few months back, please let me know if you want to be mentioned in the blog posts!

Cheers,
Marco

**Comment by bennukem** [comment]
I think my presence is not necessary but it is more interesting to talk about your change, why and how you solved your issue sound better.
To be honest, I was thinking to do a server for game like Tibia or a Dwarf Fortress like. Just to practice Rust. Of course, with your nickname, and your subject I only can find your blog ;)
